version: '3.8'

services:
  purple-test:
    build: .
    container_name: purple_os_tester
    environment:
      - DEVICE_IP=${DEVICE_IP:-192.168.1.1}
      - DEVICE_USERNAME=${DEVICE_USERNAME:-root}
      - MAX_WORKERS=${MAX_WORKERS:-10}
    volumes:
      - ./test_logs:/app/test_logs
      - ./test_reports:/app/test_reports
      - ./test_dashboards:/app/test_dashboards
      - ./results:/app/results
      - ~/.ssh:/root/.ssh:ro  # Mount SSH keys (read-only)
    networks:
      - test_network
    restart: unless-stopped
    command: python purple_os_test_native.py --device-ip ${DEVICE_IP:-192.168.1.1}

  # Optional: Web server for viewing reports
  report-server:
    image: nginx:alpine
    container_name: purple_test_reports
    ports:
      - "8080:80"
    volumes:
      - ./test_reports:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - test_network
    restart: unless-stopped

  # Optional: Scheduler for periodic tests
  scheduler:
    build: .
    container_name: purple_test_scheduler
    environment:
      - DEVICE_IP=${DEVICE_IP:-192.168.1.1}
      - TEST_SCHEDULE=${TEST_SCHEDULE:-0 */6 * * *}  # Every 6 hours
    volumes:
      - ./test_logs:/app/test_logs
      - ./test_reports:/app/test_reports
      - ./test_dashboards:/app/test_dashboards
      - ./results:/app/results
      - ~/.ssh:/root/.ssh:ro
    networks:
      - test_network
    restart: unless-stopped
    command: /app/scheduler.sh

networks:
  test_network:
    driver: bridge